# ---------------------------- CONSTANTS ------------------------------- #
PINK = "#e2979c"
RED = "#e7305b"
GREEN = "#9bdeac"
YELLOW = "#f7f5dd"
FONT_NAME = "Courier"
WHITE ="white"
FONT_SIZE = 35
BOLD = "bold"
WORK_MIN = 25
SHORT_BREAK_MIN = 5
LONG_BREAK_MIN = 20
FILE_PATH ="tomato.png"
STARTING_TIME ="00:00"
TITLE = "Pomodoro"
BREAK ="Break"
TIMER ="Timer"
CHECKMARK ="✔"
START ="Start"
RESET ="Reset"
WORK  ="Work"